"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.APP_PORT = exports.gigaScope = exports.gigaClientId = exports.DB_NAME = exports.DB_HOST = exports.DB_PASS = exports.DB_USER_NAME = void 0;
exports.DB_USER_NAME = "event_user";
exports.DB_PASS = "zB1õkIÞ´¶©iRîBp(WPiì:Þìú£+D!åx_ÛÇ";
exports.DB_HOST = "194.67.108.212";
exports.DB_NAME = "events";
exports.gigaClientId = "ZTQ2Y2E2OGYtNjNlOC00NzMwLWEyYzMtNmE0OTY0YTgwODNkOjVmMGU4YTQ3LTc3OWQtNGJiYi04Yjc0LWYzOWIwYzBhMWY5ZA==";
exports.gigaScope = "GIGACHAT_API_PERS";
exports.APP_PORT = 8002;
